name 'dhoppe-rsyslog'
version '0.0.8'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-rsyslog'
source 'git://github.com/dhoppe/puppet-rsyslog'
summary 'Rsyslog Module'
description 'Rsyslog Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
